# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sufra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sufra
pod 'SwiftLint'

  target 'SufraTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SufraUITests' do
    # Pods for testing
  end

end
